### PR TITLE
Fix axis bug

### LINKED ISSUE #17: Fix x axis date range
Choosing a range like 2022-01-11 -> 2022-01-18 picks dates in the range 2022-01-01 -> 2022-01-18 and the first part of the range is shown on the axis _after_ 2022-01-18. Stupid.

### PR DESCRIPTION
**Pull request by breedx2**
Resolves #17

Don't put data into nonexistent buckets.

### CODE REVIEW

File: web/src/aggregation.js [hunk 1]
```diff
@@ -51,13 +51,14 @@ function aggregate(data){
...
 
   const result = stubZeroBuckets(type);
-  // console.log(result);
   const agg = AGGREGATORS[type];
   data.forEach(event => {
     const ch = event['channel'].replace(/^SIP-/, '');
     const name = phoneList.phonesAreCombined() ? 'x' : phoneList.nameFromChannel(ch);
     const bucket = agg.bucket(new Date(event['timestamp']))
-    result[name][bucket] = result[name][bucket] + 1;
+    if(bucket in result[name]){
```
Comment (breedx2) [inline web/src/aggregation.js:59]: The data can contain events outside our date range, so we only want to include increment if the data falls into one of the precreated buckets.

File: web/src/graph.js [hunk 2]
```diff
@@ -13,14 +13,12 @@ async function buildAndShow(){
...
   console.log(`graphing from ${start} to ${end}`);
-  dataLoader.getRangeByMonth(start, end)
-    .then(filterToSelectedPhones)
-    .then(filterToSelectedEvents)
-    .then(aggregation.aggregate)
-    .then(data => {
-      console.log(data);
-      plot(data);
-    });
+  let data = await dataLoader.getRangeByMonth(start, end);
```
Comment (breedx2) [inline web/src/graph.js:16]: this is just a cleanup/simplification.
